<% socket_locations = %w[/opt/local/var/run/mysql5/mysqld.sock /var/lib/mysql/mysql.sock /tmp/mysql.sock] %>

development:
  adapter: mysql
  encoding: utf8
  database: traveljournal_development
  username: root
  password: root
  socket: <%= socket_locations.detect { |f| File.exists?(f) } %>

test:
  adapter: mysql
  encoding: utf8
  database: traveljournal_test
  username: root
  password: root
  socket: <%= socket_locations.detect { |f| File.exists?(f) } %>